CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    nome_completo VARCHAR(255),
    telefone VARCHAR(255),
    tentativas_falhas INTEGER,
    bloqueado_ate TIMESTAMP,
    ultimo_login TIMESTAMP,
    status VARCHAR(255),
    perfil VARCHAR(255),
    criado_em TIMESTAMP,
    atualizado_em TIMESTAMP,
    senha_alterada_em TIMESTAMP,
    CONSTRAINT uk_users_username UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS mensagens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    remetente_id BIGINT NOT NULL,
    destinatario_id BIGINT NOT NULL,
    texto TEXT,
    anexo_nome_original VARCHAR(255),
    anexo_nome_arquivo VARCHAR(255),
    anexo_content_type VARCHAR(255),
    anexo_tamanho BIGINT,
    lida BOOLEAN,
    criado_em TIMESTAMP,
    expira_em TIMESTAMP,
    CONSTRAINT fk_mensagens_remetente FOREIGN KEY (remetente_id) REFERENCES users (id),
    CONSTRAINT fk_mensagens_destinatario FOREIGN KEY (destinatario_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS carteira_digital (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registro VARCHAR(20) NOT NULL,
    cpf VARCHAR(11) NOT NULL,
    nome VARCHAR(200) NOT NULL,
    propriedade VARCHAR(255) NOT NULL,
    unloc VARCHAR(10),
    inicio_atividade TIMESTAMP,
    validade TIMESTAMP,
    endereco VARCHAR(500),
    atividade_primaria VARCHAR(255),
    atividade_secundaria VARCHAR(255),
    georeferenciamento VARCHAR(255),
    pdf_conteudo BYTEA,
    usuario VARCHAR(100),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT uk_carteira_digital_registro UNIQUE (registro)
);

CREATE TABLE IF NOT EXISTS carteira_fotos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carteira_id BIGINT,
    ordem INTEGER,
    conteudo BYTEA,
    nome_arquivo VARCHAR(255),
    content_type VARCHAR(255),
    CONSTRAINT fk_carteira_fotos_carteira FOREIGN KEY (carteira_id) REFERENCES carteira_digital (id)
);

CREATE TABLE IF NOT EXISTS carteiras_digitais (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registro VARCHAR(50),
    cpf VARCHAR(11) NOT NULL,
    nome VARCHAR(200) NOT NULL,
    propriedade VARCHAR(255),
    unloc VARCHAR(20),
    inicio VARCHAR(10),
    validade VARCHAR(10),
    endereco VARCHAR(500),
    atividade1 TEXT,
    atividade2 TEXT,
    georef TEXT,
    pdf_conteudo BYTEA,
    foto1 BYTEA,
    foto2 BYTEA,
    foto3 BYTEA,
    usuario VARCHAR(100),
    criado_em TIMESTAMP,
    atualizado_em TIMESTAMP
);

CREATE TABLE IF NOT EXISTS inscricoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    cpf VARCHAR(255),
    municipio VARCHAR(255),
    memorando VARCHAR(255),
    latitude VARCHAR(255),
    longitude VARCHAR(255),
    tipo VARCHAR(255),
    criado_em TIMESTAMP
);

CREATE TABLE IF NOT EXISTS analises (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero VARCHAR(255),
    titulo VARCHAR(255),
    motivo VARCHAR(255),
    localidade VARCHAR(255),
    prioridade VARCHAR(255),
    status VARCHAR(255),
    memorando_pdf TEXT,
    aberto_por VARCHAR(255),
    recebido_em TIMESTAMP,
    aberto_em TIMESTAMP,
    finalizado_em TIMESTAMP
);

CREATE TABLE IF NOT EXISTS analise_processos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produtor VARCHAR(255),
    cpf VARCHAR(255),
    processo_pdf TEXT,
    declaracao_pdf TEXT,
    data_declaracao DATE,
    recebido_em DATE,
    tipo_identificado VARCHAR(255),
    gcc_status VARCHAR(255),
    dados_gcc_conferidos BOOLEAN,
    observacao TEXT,
    observacao_atualizada_em TIMESTAMP,
    decisao VARCHAR(255),
    motivo_devolucao VARCHAR(255),
    decisao_responsavel VARCHAR(255),
    decisao_em TIMESTAMP,
    encaminhado_para VARCHAR(255),
    encaminhado_em TIMESTAMP,
    checklist_incompleto BOOLEAN,
    gcc_divergente BOOLEAN,
    declaracao_vencida BOOLEAN,
    declaracao_futura BOOLEAN,
    cpf_divergente BOOLEAN,
    analise_id BIGINT,
    CONSTRAINT fk_analise_processos_analise FOREIGN KEY (analise_id) REFERENCES analises (id)
);

CREATE TABLE IF NOT EXISTS analise_encaminhamentos (
    id VARCHAR(255) PRIMARY KEY,
    analise_id BIGINT,
    memorando_numero VARCHAR(255),
    memorando_titulo VARCHAR(255),
    memorando_pdf TEXT,
    processo_id BIGINT,
    produtor VARCHAR(255),
    cpf VARCHAR(255),
    localidade VARCHAR(255),
    processo_pdf TEXT,
    declaracao_pdf TEXT,
    tipo_identificado VARCHAR(255),
    resultado_consulta VARCHAR(255),
    data_declaracao VARCHAR(255),
    recebido_em TIMESTAMP,
    encaminhado_em TIMESTAMP,
    destino VARCHAR(255),
    motivo VARCHAR(255),
    observacao TEXT
);

CREATE TABLE IF NOT EXISTS memorandos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero VARCHAR(255),
    descricao VARCHAR(255),
    unloc VARCHAR(255),
    municipio VARCHAR(255),
    memo_entrada VARCHAR(255),
    data_emissao DATE,
    quantidade INTEGER,
    usuario VARCHAR(255),
    criado_em TIMESTAMP,
    arquivo_word BYTEA
);

CREATE TABLE IF NOT EXISTS fluxo_processos (
    id VARCHAR(40) PRIMARY KEY,
    produtor VARCHAR(180) NOT NULL,
    cpf VARCHAR(14) NOT NULL,
    tipo_processo VARCHAR(30) NOT NULL,
    unidade_local VARCHAR(120) NOT NULL,
    tecnico_responsavel VARCHAR(120) NOT NULL,
    situacao VARCHAR(40) NOT NULL,
    formulario VARCHAR(255),
    fac VARCHAR(255),
    declaracao_produtor VARCHAR(255),
    declaracoes VARCHAR(255),
    documentos_gerados_json TEXT,
    fac_status VARCHAR(40),
    fac_gerada_em TIMESTAMP,
    fac_gerada_por VARCHAR(255),
    fac_impressa_em TIMESTAMP,
    fac_impressa_por VARCHAR(255),
    fac_assinada_anexada_em TIMESTAMP,
    fac_assinada_anexada_por VARCHAR(255),
    fac_assinada_documento_id VARCHAR(255),
    fac_rejeitada_motivo TEXT,
    memorando_arquivo VARCHAR(255),
    memorando_criado_em TIMESTAMP,
    memorando_quantidade INTEGER,
    memorando_produtores_json TEXT,
    memorandos_json TEXT,
    memorando_numero VARCHAR(255),
    memorando_lote_id VARCHAR(255),
    gerente_responsavel VARCHAR(255),
    gerente_assinado_em TIMESTAMP,
    assinatura_eletronica_json TEXT,
    encaminhado_gerente_em TIMESTAMP,
    enviado_analise_em TIMESTAMP,
    analista_responsavel VARCHAR(255),
    analisado_em TIMESTAMP,
    lancado_por VARCHAR(255),
    lancado_em TIMESTAMP,
    ultima_justificativa TEXT,
    criado_em TIMESTAMP,
    atualizado_em TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fluxo_documentos (
    id VARCHAR(40) PRIMARY KEY,
    processo_id VARCHAR(40) NOT NULL,
    nome VARCHAR(160) NOT NULL,
    arquivo VARCHAR(240) NOT NULL,
    obrigatorio BOOLEAN,
    categoria VARCHAR(40) NOT NULL,
    mime_type VARCHAR(255),
    tamanho BIGINT,
    conteudo TEXT,
    criado_em TIMESTAMP,
    CONSTRAINT fk_fluxo_documentos_processo FOREIGN KEY (processo_id) REFERENCES fluxo_processos (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS fluxo_historico (
    id VARCHAR(40) PRIMARY KEY,
    processo_id VARCHAR(40) NOT NULL,
    usuario VARCHAR(120) NOT NULL,
    acao VARCHAR(180) NOT NULL,
    data_hora TIMESTAMP,
    observacao TEXT,
    CONSTRAINT fk_fluxo_historico_processo FOREIGN KEY (processo_id) REFERENCES fluxo_processos (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS fluxo_gerentes_unidade (
    id VARCHAR(40) PRIMARY KEY,
    nome VARCHAR(160) NOT NULL,
    unidade_local VARCHAR(120) NOT NULL,
    cargo VARCHAR(120) NOT NULL,
    telefone_corporativo VARCHAR(255),
    telefone_pessoal VARCHAR(255),
    status VARCHAR(30) NOT NULL,
    cadastrado_em TIMESTAMP,
    encerrado_em TIMESTAMP,
    atualizado_em TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_mensagens_destinatario_criado_em
    ON mensagens (destinatario_id, criado_em);
CREATE INDEX IF NOT EXISTS idx_mensagens_remetente_criado_em
    ON mensagens (remetente_id, criado_em);
CREATE INDEX IF NOT EXISTS idx_fluxo_processos_situacao
    ON fluxo_processos (situacao);
CREATE INDEX IF NOT EXISTS idx_fluxo_processos_cpf
    ON fluxo_processos (cpf);
CREATE INDEX IF NOT EXISTS idx_fluxo_documentos_processo
    ON fluxo_documentos (processo_id);
CREATE INDEX IF NOT EXISTS idx_fluxo_historico_processo_data
    ON fluxo_historico (processo_id, data_hora);
CREATE INDEX IF NOT EXISTS idx_analise_processos_analise
    ON analise_processos (analise_id);
