CREATE TABLE IF NOT EXISTS auditoria_eventos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ocorreu_em TIMESTAMP NOT NULL,
    usuario VARCHAR(120),
    acao VARCHAR(120) NOT NULL,
    recurso_tipo VARCHAR(80),
    recurso_id VARCHAR(160),
    metodo_http VARCHAR(12),
    caminho VARCHAR(500),
    status_http INTEGER,
    resultado VARCHAR(40) NOT NULL,
    ip_origem VARCHAR(80),
    user_agent VARCHAR(500),
    correlation_id VARCHAR(120),
    detalhes TEXT
);

CREATE INDEX IF NOT EXISTS idx_auditoria_eventos_ocorreu_em
    ON auditoria_eventos (ocorreu_em);

CREATE INDEX IF NOT EXISTS idx_auditoria_eventos_usuario_ocorreu_em
    ON auditoria_eventos (usuario, ocorreu_em);

CREATE INDEX IF NOT EXISTS idx_auditoria_eventos_acao_ocorreu_em
    ON auditoria_eventos (acao, ocorreu_em);

CREATE INDEX IF NOT EXISTS idx_auditoria_eventos_recurso
    ON auditoria_eventos (recurso_tipo, recurso_id);
